version: "3"

services:
  web:
    build: .
    image: nidhalnouma/tradingrev
    ports:
      - "8080:8080"
  admin:
    build: ./Admin/admin
    image: nidhalnouma/admintr
    ports:
      - "3909:3000"
    links:
      - web
